const descriptions: Record<string, string> = {
  "--add-npm-scripts": "Add npm script shortcuts during initialization.",
  "--allow-dirty": "Allow running while the working tree has changes.",
  "--allow-open-findings": "Allow superseding work with unresolved findings.",
  "--allow-scripts": "Allow preset script execution.",
  "--anchor": "Select the decision anchor id used as a relation source.",
  "--append": "Append a JSON value to a schema-declared amendable field.",
  "--apply": "Apply the operation instead of planning it.",
  "--archive": "Archive generated governance output.",
  "--archive-field": "Set the field used for archive disposition.",
  "--archived-by": "Record the actor archiving the task.",
  "--arbiter": "Set the decision arbiter as agent:<id>, human:<id>, or system:<id>.",
  "--assume-locale": "Set the assumed locale for migrated content.",
  "--base": "Set the git base ref.",
  "--branch": "Set the module branch.",
  "--body": "Set authored body content for the generated decision document.",
  "--by": "Set the replacing task or invalidating fact id.",
  "--catalog": "Use a template catalog file.",
  "--candidate": "Read a generated distill candidate artifact.",
  "--chosen": "Set the selected decision option text.",
  "--ci": "Set the completion CI gate result.",
  "--claim": "Set the primary supporting claim text for a decision.",
  "--compact": "Return only cold-start summary fields for list commands.",
  "--confirm": "Confirm a destructive or relation-changing action.",
  "--confirm-plan": "Confirm a migration plan before applying it.",
  "--current-step": "Set the current module step.",
  "--decided-at": "Set the decision timestamp for transition commands.",
  "--deleted-by": "Record the actor deleting or superseding the task.",
  "--detected-at": "Set the detected session timestamp for explicit session export.",
  "--depends-on": "Register a module dependency.",
  "--dry-run": "Preview the operation without writing changes.",
  "--evidence": "Attach evidence in type:path:summary format.",
  "--evidence-relation": "Attach a decision anchor to a task, decision, or fact ref as anchor:type:target:rationale; repeat for multiple relations.",
  "--confidence": "Set fact confidence as low, medium, or high.",
  "--approval": "Record a runtime event approval decision.",
  "--at": "Set the runtime event timestamp.",
  "--interrupt": "Record a task-level interrupt or steering action.",
  "--kind": "Set the runtime event kind.",
  "--result": "Record a runtime event result status.",
  "--runtime": "Set the observed runtime kind.",
  "--session": "Set the runtime session id.",
  "--step": "Set the observed runtime step id.",
  "--summary": "Set a short structured summary.",
  "--tool": "Set the observed tool or command name.",
  "--total-tokens": "Set the observed total token count.",
  "--turn": "Set the observed runtime turn id.",
  "--force": "Force the lifecycle transition with audit metadata.",
  "--focus": "Focus graph output on one entity ref and include F5 cascade impact.",
  "--from-file": "Read command input JSON from a file; flags remain shortcut overrides.",
  "--from-legacy": "Create from a legacy task id.",
  "--hard": "Hard-delete the selected task.",
  "--help": "Show help output.",
  "--id": "Set the explicit entity id when the command supports one.",
  "--include-archived": "Include archived task packages.",
  "--input": "Provide an input path or one script input as key=value; repeat for script inputs.",
  "--json": "Emit command-receipt/v2 JSON.",
  "--json-input": "Read command input JSON from an inline string; flags remain shortcut overrides.",
  "--kernel-version": "Validate against a kernel version.",
  "--legacy-id": "Filter decisions by migrated legacy E number, such as E72.",
  "--legacy-range": "Filter decisions by an inclusive migrated legacy E-number range, such as E1-E71.",
  "--lesson": "Filter by lesson state.",
  "--limit": "Limit the number of planned items.",
  "--locale": "Set generated content locale.",
  "--long-running": "Mark the task as long-running.",
  "--memory-class": "Classify fact memory as semantic, episodic, or procedural.",
  "--memory-tag": "Attach a fact memory tag; repeat or comma-separate values.",
  "--missing-materials": "Filter tasks missing required materials.",
  "--module": "Select a registered module key; use module list to discover keys.",
  "--module-scope": "Set the registered module source scope, such as packages/name/**.",
  "--module-title": "Set the human-readable title for a registered module.",
  "--name": "Set the project name written to harness.yaml.",
  "--observed-at": "Set the observation timestamp for a fact record.",
  "--out": "Write the generated plan to a file.",
  "--out-dir": "Set the output directory.",
  "--owner": "Set the module owner.",
  "--parent": "Bind a new task to an existing parent task id.",
  "--plan": "Plan without applying changes.",
  "--plan-only": "Create a migration plan without applying it.",
  "--post-merge": "Run checks intended for post-merge validation.",
  "--prefix": "Set the module id prefix.",
  "--preset": "Select a preset id; task create defaults to standard-task and preset list shows installed presets.",
  "--product-line": "Attach a comma-separated product line list to a decision.",
  "--profile": "Select a check or task profile; task create defaults to baseline.",
  "--projection": "Read a specific SQLite projection file instead of the default harness projection cache.",
  "--project": "Use the project preset layer.",
  "--proposed-by": "Set the decision proposer as agent:<id>, human:<id>, or system:<id>.",
  "--purpose": "Filter script entries by declared purpose.",
  "--question": "Set the decision question being answered.",
  "--queue": "Filter by queue.",
  "--reason": "Record the reason for the lifecycle change.",
  "--rationale": "Record the rationale for a relation or generated decision.",
  "--rejected": "Set a rejected decision option text.",
  "--register-module": "Register a module while creating the task.",
  "--relation": "Select a hosted relation id.",
  "--review": "Filter by review state.",
  "--reviewer": "Set the reviewer id.",
  "--risk-tier": "Set decision risk tier as low, medium, or high.",
  "--search": "Search task metadata and prose.",
  "--session-dir": "Set the migration session directory.",
  "--set": "Replace a schema-declared amendable field value.",
  "--shared": "Register a shared path for the module.",
  "--slug": "Set the task slug.",
  "--scope": "Set the module scope.",
  "--soft": "Soft-delete the selected task.",
  "--source": "Set the fact evidence source or filter extension entries by source layer.",
  "--state": "Set or filter by state. Valid task states: planned, active, blocked, in_review, done, cancelled.",
  "--statement": "Set the fact statement text.",
  "--status": "Set the external or module status.",
  "--strict": "Run strict checks.",
  "--task": "Set the task id.",
  "--target": "Set the relation target entity ref.",
  "--text": "Progress text appended as-is (no Markdown formatting or normalization).",
  "--title": "Set the required task title used for generated package metadata and slug.",
  "--type": "Set the relation type. Valid relation types: supports, supersedes, refines, narrows, derives, blocks, relates, implements, depends-on, produces, evidences, evidenced-by, invalidated-by, supersedes-fact.",
  "--urgency": "Set decision urgency as low, medium, or high.",
  "--user": "Set the user label for explicit session export.",
  "--vertical": "Select a vertical definition; task create defaults to software/coding.",
  "--version": "Print the installed CLI version.",
  "--why-not": "Set the rationale for rejecting the alternative.",
  "--write": "Persist the generated artifact instead of returning a dry-run report."
};

export function optionDescription(flag: string): string {
  const description = descriptions[flag];
  if (!description) {
    throw new Error(`missing CLI help option description: ${flag}`);
  }
  return description;
}
