import type { CommandKind } from "./command-registry.ts";
import type { ParsedCommand } from "./types.ts";

export type RuntimeEventPolicy = "auto" | "direct" | "none" | "deferred";

const conflictMarkerPreflightByKind = {
  help: false,
  version: false,
  init: true,
  "new-task": true,
  "status-set": true,
  "progress-append": true,
  "task-archive": true,
  "task-supersede": true,
  "task-delete": true,
  "task-reopen": true,
  "task-review": true,
  "task-complete": true,
  "decision-list": false,
  "decision-show": false,
  "decision-propose": true,
  "decision-accept": true,
  "decision-reject": true,
  "decision-defer": true,
  "decision-supersede": true,
  "decision-amend": true,
  "decision-relate": true,
  "decision-retire": true,
  "record-fact": true,
  "distill-candidate": true,
  "distill-commit": true,
  "runtime-event-append": true,
  "runtime-event-list": false,
  "doc-list": false,
  "doc-map": false,
  "template-list": false,
  "template-render": false,
  "task-list": true,
  status: true,
  check: false,
  "governance-rebuild": true,
  "lesson-promote": true,
  "lesson-sediment": true,
  "adopt-multica": true,
  "snapshot-multica": false,
  "migrate-plan": false,
  "migrate-structure": true,
  "migrate-provenance": true,
  "migrate-run": true,
  "migrate-verify": false,
  "legacy-scan": false,
  "legacy-intake-plan": true,
  "legacy-copy-safe-docs": true,
  "legacy-index": true,
  "legacy-verify": false,
  "git-diff": false,
  doctor: false,
  graph: false,
  "entity-list": false,
  capabilities: false,
  "preset-validate": false,
  "preset-list": false,
  "preset-inspect": false,
  "preset-check": false,
  "preset-install": true,
  "preset-seed": true,
  "preset-audit": false,
  "preset-uninstall": true,
  "preset-run": true,
  "preset-action": true,
  "script-list": false,
  "script-inspect": false,
  "script-run": true,
  "module-list": false,
  "module-inspect": false,
  "module-register": true,
  "module-scaffold": true,
  "module-unregister": true,
  "module-step": true,
  "vertical-validate": false,
  gui: false
} as const satisfies Record<CommandKind, boolean>;

const runtimeEventPolicyByKind = {
  help: "none",
  version: "none",
  init: "deferred",
  "new-task": "auto",
  "status-set": "auto",
  "progress-append": "auto",
  "task-archive": "auto",
  "task-supersede": "auto",
  "task-delete": "auto",
  "task-reopen": "auto",
  "task-review": "auto",
  "task-complete": "auto",
  "decision-list": "none",
  "decision-show": "none",
  "decision-propose": "auto",
  "decision-accept": "auto",
  "decision-reject": "auto",
  "decision-defer": "auto",
  "decision-supersede": "auto",
  "decision-amend": "auto",
  "decision-relate": "auto",
  "decision-retire": "auto",
  "record-fact": "auto",
  "distill-candidate": "auto",
  "distill-commit": "auto",
  "runtime-event-append": "direct",
  "runtime-event-list": "none",
  "doc-list": "none",
  "doc-map": "none",
  "template-list": "none",
  "template-render": "none",
  "task-list": "none",
  status: "none",
  check: "none",
  "governance-rebuild": "deferred",
  "lesson-promote": "deferred",
  "lesson-sediment": "deferred",
  "adopt-multica": "deferred",
  "snapshot-multica": "none",
  "migrate-plan": "none",
  "migrate-structure": "deferred",
  "migrate-provenance": "deferred",
  "migrate-run": "deferred",
  "migrate-verify": "none",
  "legacy-scan": "none",
  "legacy-intake-plan": "deferred",
  "legacy-copy-safe-docs": "deferred",
  "legacy-index": "deferred",
  "legacy-verify": "none",
  "git-diff": "none",
  doctor: "none",
  graph: "none",
  "entity-list": "none",
  capabilities: "none",
  "preset-validate": "none",
  "preset-list": "none",
  "preset-inspect": "none",
  "preset-check": "none",
  "preset-install": "deferred",
  "preset-seed": "deferred",
  "preset-audit": "none",
  "preset-uninstall": "deferred",
  "preset-run": "deferred",
  "preset-action": "deferred",
  "script-list": "none",
  "script-inspect": "none",
  "script-run": "deferred",
  "module-list": "none",
  "module-inspect": "none",
  "module-register": "auto",
  "module-scaffold": "auto",
  "module-unregister": "auto",
  "module-step": "auto",
  "vertical-validate": "none",
  gui: "none"
} as const satisfies Record<CommandKind, RuntimeEventPolicy>;

export function requiresConflictMarkerPreflight(action: ParsedCommand["action"] | CommandKind): boolean {
  return conflictMarkerPreflightByKind[commandKind(action)];
}

export function runtimeEventPolicyForAction(action: ParsedCommand["action"] | CommandKind): RuntimeEventPolicy {
  const kind = commandKind(action);
  const policy = runtimeEventPolicyByKind[kind];
  if (policy !== "auto") return policy;
  return typeof action === "string" || !isDryRun(action) ? "auto" : "none";
}

function commandKind(action: ParsedCommand["action"] | CommandKind): CommandKind {
  return typeof action === "string" ? action : action.kind;
}

function isDryRun(action: ParsedCommand["action"]): boolean {
  return "dryRun" in action && action.dryRun === true;
}
