import { Schema } from "effect";
import { TemplateCatalogSchema, VerticalDefinitionSchema } from "../../../../kernel/src/index.ts";

type TemplateCatalog = Schema.Schema.Type<typeof TemplateCatalogSchema>;
type VerticalDefinition = Schema.Schema.Type<typeof VerticalDefinitionSchema>;

const taskPlanZh = `# {{title}}

Task Contract: harness-task v1

## Goal

说明本任务要完成的可验证结果。

## Context

记录输入背景、相关约束和不应改变的边界。

## Implementation Plan

- 确认现有代码和契约。
- 以最小范围实现变更。
- 用测试和检查验证行为。

## Verification

- 记录本任务需要通过的本地检查、CI 和人工审查。
`;

const taskPlanEn = `# {{title}}

Task Contract: harness-task v1

## Goal

Describe the verifiable result this task must produce.

## Context

Record input context, relevant constraints, and boundaries that must not change.

## Implementation Plan

- Inspect existing code and contracts.
- Implement the change with minimal scope.
- Verify behavior with tests and checks.

## Verification

- Record required local checks, CI, and review evidence for this task.
`;

const progressBody = `# Progress

## Log

- Record key implementation steps, verification results, and blockers.

## Evidence

| ID | Type | Evidence | Status |
| --- | --- | --- | --- |
`;

const reviewBody = `# Review

Status: not-started

## Reviewer

- Agent: pending
- Mode: read-only code review before merge

## Findings

| ID | Severity | Finding | Evidence Checked | Required Action | Open | Disposition | Blocks Release | Follow-up |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
`;

const closeoutBody = `# Closeout

## Summary

Summarize the completed behavior change.

## Verification

List passing checks and CI.

## Residual Risk

Record accepted non-blocking risks.
`;

const referencesBody = `# References

## Inputs

- List design, requirement, review, and external context.
`;

const artifactsBody = `# Artifacts

## Generated

- List evidence, reports, and outputs generated by this task.
`;

export const bundledSoftwareCodingTemplateCatalog = Schema.decodeUnknownSync(TemplateCatalogSchema)({
  schema: "template-catalog/v1",
  package: {
    id: "software-coding-core",
    title: "Software Coding Core Templates",
    version: "1.0.0",
    owner: "harness-anything",
    locales: ["zh-CN", "en-US"]
  },
  documents: [
    templateDocument("planning/task-plan", "1", "task-plan", "task.plan", "task_plan.md", ["## Goal", "## Context", "## Implementation Plan", "## Verification"], taskPlanZh, taskPlanEn),
    templateDocument("planning/progress", "1", "progress-log", "task.progress", "progress.md", ["## Log", "## Evidence"], progressBody, progressBody),
    templateDocument("planning/review", "1", "review-log", "task.review", "review.md", ["## Reviewer", "## Findings"], reviewBody, reviewBody),
    templateDocument("planning/closeout", "1", "closeout", "task.closeout", "closeout.md", ["## Summary", "## Verification", "## Residual Risk"], closeoutBody, closeoutBody),
    templateDocument("planning/references-index", "1", "references-index", "task.references.index", "references/INDEX.md", ["## Inputs"], referencesBody, referencesBody),
    templateDocument("planning/artifacts-index", "1", "artifacts-index", "task.artifacts.index", "artifacts/INDEX.md", ["## Generated"], artifactsBody, artifactsBody)
  ]
} satisfies TemplateCatalog);

export const bundledSoftwareCodingVerticalDefinition = Schema.decodeUnknownSync(VerticalDefinitionSchema)({
  schema: "vertical-definition/v1",
  id: "software/coding",
  title: "Software Coding",
  version: "1.0.0",
  entityKinds: [
    { id: "task", packageKind: "task-package/v2", contractEntity: true },
    { id: "decision-record", packageKind: "document/v1", contractEntity: false }
  ],
  contractEntityKinds: ["task"],
  packageScaffolds: [{
    entityKind: "task",
    templateSelections: taskTemplateSelections()
  }],
  templateSelections: taskTemplateSelections(),
  checkerProfile: "software-coding-standard",
  projectionSchemas: [
    { id: "task-frontmatter", schemaRef: "schema://task-frontmatter" }
  ]
} satisfies VerticalDefinition);

export function bundledTemplateCatalog(id?: string): TemplateCatalog | undefined {
  if (!id || id === "software/coding" || id === "software-coding-core") return bundledSoftwareCodingTemplateCatalog;
  return undefined;
}

export function bundledVerticalDefinition(id?: string): VerticalDefinition | undefined {
  if (!id || id === "software/coding") return bundledSoftwareCodingVerticalDefinition;
  return undefined;
}

export function bundledTaskTemplateSelections(): VerticalDefinition["templateSelections"] {
  return taskTemplateSelections();
}

function templateDocument(
  id: string,
  version: string,
  documentKind: string,
  slot: string,
  materializeAs: string,
  requiredAnchors: ReadonlyArray<string>,
  zhBody: string,
  enBody: string
): TemplateCatalog["documents"][number] {
  return {
    id,
    version,
    documentKind,
    slot,
    materializeAs,
    frontmatterSchema: "task-package/v2",
    requiredAnchors,
    fallbackLocale: "en-US",
    locales: [
      { locale: "zh-CN", anchors: requiredAnchors, body: zhBody },
      { locale: "en-US", anchors: requiredAnchors, body: enBody }
    ]
  };
}

function taskTemplateSelections(): VerticalDefinition["templateSelections"] {
  return bundledSoftwareCodingTemplateCatalog.documents.map((document) => ({
    slot: document.slot,
    templateRef: `template://${document.id}@${document.version}`,
    materializeAs: document.materializeAs,
    localePolicy: {
      prefer: "project",
      fallback: "en-US"
    }
  }));
}
