/**
 * 一键复制上下文(W2B §3)。
 *
 * 产出一段 agent 能直接干活的可粘贴文本:相关 task/decision/fact 的 ID + 摘要 + 当前问题上下文。
 * 人自己起 coding agent 粘贴(rejected 红线:不注入终端/不预填命令)。
 */

import type { DecisionRow, FactRef, RelationEdge, TaskRow } from "./types";
import type { FactTriageItem } from "./fact-triage";
import { SIGNAL_LABEL } from "./fact-triage";
import { normalizeDecisionId } from "./triadic";
import { t } from "../i18n/core.ts";

/**
 * 为一条 triage fact 构造 agent 可用的上下文包。
 *
 * @param item triage 排好序的 fact 项(含信号)
 * @param relations 全量 relation 边
 * @param decisions 全量 decision
 * @param tasks 全量 task
 * @returns markdown 格式的上下文文本(已去尾换行)
 */
export function buildFactTriageContext(
  item: FactTriageItem,
  relations: RelationEdge[],
  decisions: DecisionRow[],
  tasks: TaskRow[],
): string {
  const { fact, signals, citingDecisionIds } = item;
  const lines: string[] = [];

  const signalSummary = signals
    .map((s) => `${SIGNAL_LABEL[s.kind]}: ${s.detail}`)
    .join("; ");

  lines.push(t("model.copyContext.harnessContextFactTriageSignal"));
  lines.push("");
  lines.push(`**fact anchor**: \`${fact.anchor}\``);
  lines.push(t("model.copyContext.exceptionSignalSignalSummary", { signalSummary: signalSummary }));
  lines.push(t("model.copyContext.currentProblemFactScreenedByMachineAs"));
  lines.push("");

  // --- Fact 本体 ---
  lines.push(t("model.copyContext.factObservation"));
  lines.push(`- **anchor**: \`${fact.anchor}\``);
  lines.push(t("model.copyContext.observationText", { text: fact.text }));
  lines.push(`- **category**: ${fact.category}`);
  lines.push(`- **observed at**: ${fact.at}`);
  lines.push(`- **confidence**: ${fact.confidence}`);
  lines.push(`- **invalidated**: ${fact.invalidated ? t("model.copyContext.yes") : t("model.copyContext.no")}`);
  lines.push("");

  // --- 来源 task ---
  const sourceTask = tasks.find((t) => t.taskId === fact.taskId);
  lines.push(t("model.copyContext.sourceTask"));
  if (sourceTask) {
    lines.push(`- **id**: \`${sourceTask.taskId}\``);
    lines.push(`- **title**: ${sourceTask.title}`);
    lines.push(`- **module**: ${sourceTask.module}`);
    lines.push(`- **coordinationStatus**: ${sourceTask.coordinationStatus}`);
    lines.push(`- **closeoutReadiness**: ${sourceTask.closeoutReadiness}`);
    const failedGates = sourceTask.gates.filter((g) => !g.ok);
    if (failedGates.length > 0) {
      lines.push(
        `- **failed gates**: ${failedGates.map((g) => g.name).join(", ")}`,
      );
    }
  } else {
    lines.push(t("model.copyContext.idTaskIdHostTaskNotCurrentlyProjected", { taskId: fact.taskId }));
  }
  lines.push("");

  // --- 相关 decision ---
  const fullRef = `fact/${fact.anchor}`;
  const citingDecisions = decisions.filter((d) =>
    citingDecisionIds.includes(d.decisionId),
  );
  lines.push(t("model.copyContext.relatedDecisionsCount", { count: citingDecisions.length }));
  if (citingDecisions.length === 0) {
    lines.push(t("model.copyContext.noneFactNotReferencedByAnyDecision"));
  } else {
    for (const dec of citingDecisions) {
      lines.push(
        `- \`decision/${dec.decisionId}\` — ${dec.title} [state: ${dec.state}, risk: ${dec.riskTier ?? t("model.copyContext.unknown")}]`,
      );
      lines.push(`  - Q: ${dec.question}`);
    }
  }
  lines.push("");

  // --- 相关 relation 边(该 fact 直接连接的) ---
  const directEdges = relations.filter(
    (r) => r.from === fullRef || r.to === fullRef,
  );
  lines.push(t("model.copyContext.relatedRelationCount", { count: directEdges.length }));
  for (const r of directEdges) {
    const rationale = r.rationale ? ` — ${r.rationale}` : "";
    lines.push(`- \`${r.from}\` --(${r.kind})--> \`${r.to}\`${rationale}`);
  }
  lines.push("");

  // --- 行动提示(人判) ---
  lines.push(t("model.copyContext.needSomeoneJudge"));
  lines.push(
    t("model.copyContext.factTriggersTriageSignalValuePleaseJudge", { value: signals.map((s) => SIGNAL_LABEL[s.kind]).join(", ") }),
  );
  lines.push(
    t("model.copyContext.signalTrueExceptionMislabeledObsoleteFixed"),
  );
  lines.push(t("model.copyContext.itNecessarySupplementEvidenceAmendFactsVeto"));
  lines.push("");

  const footer = `<!-- generated by harness GUI fact triage · task_01KX5NENBBTC15NVRHJXB5F5S0 -->`;
  lines.push(footer);

  return lines.join("\n");
}

/**
 * 通用 entity 跳转上下文(用于活链接复制的轻量版)。
 * 给定任意 entity ref,产出 ID + 摘要 + 直连边。
 */
export function buildEntityJumpContext(
  ref: string,
  relations: RelationEdge[],
  decisions: DecisionRow[],
  facts: FactRef[],
  tasks: TaskRow[],
  problem = t("model.copyContext.entitySStatusRelationshipsEvidenceBeingChecked"),
): string {
  const lines: string[] = [];
  lines.push(`## Harness context — entity`);
  lines.push("");
  lines.push(`**ref**: \`${ref}\``);
  lines.push(t("model.copyContext.currentProblemProblem", { problem: problem }));
  lines.push("");

  if (ref.startsWith("decision/")) {
    const decId = normalizeDecisionId(ref);
    const dec = decisions.find((d) => d.decisionId === decId);
    lines.push(`### Decision`);
    if (dec) {
      lines.push(`- **id**: \`${dec.decisionId}\``);
      lines.push(`- **title**: ${dec.title}`);
      lines.push(`- **state**: ${dec.state}`);
      lines.push(`- **question**: ${dec.question}`);
    } else {
      lines.push(t("model.copyContext.decIdNotCurrentProjection", { decId: decId }));
    }
  } else if (ref.startsWith("fact/")) {
    const anchor = ref.replace(/^fact\//, "");
    const fact = facts.find((f) => f.anchor === anchor);
    lines.push(`### Fact`);
    if (fact) {
      lines.push(`- **anchor**: \`${fact.anchor}\``);
      lines.push(t("model.copyContext.observationText", { text: fact.text }));
      lines.push(`- **category**: ${fact.category}`);
      lines.push(`- **confidence**: ${fact.confidence}`);
      lines.push(`- **invalidated**: ${fact.invalidated ? t("model.copyContext.yes") : t("model.copyContext.no")}`);
      const hostTask = tasks.find((candidate) => candidate.taskId === fact.taskId);
      lines.push(
        t("model.copyContext.hostTaskTaskIdValue", {
          taskId: fact.taskId,
          value: hostTask ? ` — ${hostTask.title}` : t("model.copyContext.notProjectedCurrentTask"),
        }),
      );
    } else {
      lines.push(t("model.copyContext.anchorNotCurrentProjection", { anchor: anchor }));
    }
  } else {
    const taskId = ref.replace(/^task\//, "").split("/")[0];
    const task = tasks.find((t) => t.taskId === taskId);
    lines.push(`### Task`);
    if (task) {
      lines.push(`- **id**: \`${task.taskId}\``);
      lines.push(`- **title**: ${task.title}`);
      lines.push(`- **module**: ${task.module}`);
    } else {
      lines.push(t("model.copyContext.taskIdNotCurrentProjection", { taskId: taskId }));
    }
  }
  lines.push("");

  const directEdges = relations.filter(
    (relation) =>
      endpointBelongsToEntity(relation.from, ref) ||
      endpointBelongsToEntity(relation.to, ref),
  );
  lines.push(t("model.copyContext.directConnectionRelationCount", { count: directEdges.length }));
  for (const r of directEdges) {
    const rationale = r.rationale ? ` — ${r.rationale}` : "";
    lines.push(`- \`${r.from}\` --(${r.kind})--> \`${r.to}\`${rationale}`);
  }

  const relatedRefs = [
    ...new Set(
      directEdges.flatMap((relation) => [relation.from, relation.to]),
    ),
  ].filter((candidate) => !endpointBelongsToEntity(candidate, ref));
  lines.push("");
  lines.push(t("model.copyContext.relatedEntitiesCount", { count: relatedRefs.length }));
  if (relatedRefs.length === 0) lines.push(t("model.copyContext.noDirectlyConnectedEntity"));
  for (const relatedRef of relatedRefs) {
    lines.push(`- ${entitySummary(relatedRef, decisions, facts, tasks)}`);
  }

  return lines.join("\n");
}

function endpointBelongsToEntity(endpoint: string, entityRef: string): boolean {
  if (entityRef.startsWith("decision/")) {
    return (
      endpoint.startsWith("decision/") &&
      normalizeDecisionId(endpoint) === normalizeDecisionId(entityRef)
    );
  }
  if (entityRef.startsWith("fact/")) return endpoint === entityRef;
  const taskId = entityRef.replace(/^task\//, "").split("/")[0];
  return endpoint.replace(/^task\//, "").split("/")[0] === taskId;
}

function entitySummary(
  ref: string,
  decisions: DecisionRow[],
  facts: FactRef[],
  tasks: TaskRow[],
): string {
  if (ref.startsWith("decision/")) {
    const id = normalizeDecisionId(ref);
    const decision = decisions.find((candidate) => candidate.decisionId === id);
    return decision
      ? `\`${ref}\` — ${decision.title} [decision:${decision.state}]`
      : t("model.copyContext.refDecisionNotCurrentProjection", { ref: ref });
  }
  if (ref.startsWith("fact/")) {
    const anchor = ref.replace(/^fact\//, "");
    const fact = facts.find((candidate) => candidate.anchor === anchor);
    return fact
      ? `\`${ref}\` — ${fact.text} [fact:${fact.confidence}]`
      : t("model.copyContext.refFactNotCurrentProjection", { ref: ref });
  }
  const taskId = ref.replace(/^task\//, "").split("/")[0];
  const task = tasks.find((candidate) => candidate.taskId === taskId);
  return task
    ? `\`task/${taskId}\` — ${task.title} [task:${task.coordinationStatus}]`
    : t("model.copyContext.taskTaskIdTaskNotCurrentProjection", { taskId: taskId });
}
