/* 移植自 operator-gui-v2 原型：项目 / 任务 / 关系 mock 数据 */
import type {
  TaskRow,
  DocEntry,
  Project,
} from "./types";
import { t } from "../i18n/core.ts";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "harness-anything",
    name: "harness-anything",
    path: "~/Projects/coding-agent-harness/harness-anything",
    preset: "harness-rewrite",
    engines: ["local", "multica"],
    watermarkAt: "2026-06-12T10:02:00",
  },
  {
    id: "coding-agent-harness",
    name: "coding-agent-harness",
    path: "~/Projects/coding-agent-harness",
    preset: "docs-default",
    engines: ["local", "multica"],
    watermarkAt: "2026-06-12T09:40:00",
  },
  {
    id: "rag-pipeline-svc",
    name: "rag-pipeline-svc",
    path: "~/Projects/rag-pipeline-svc",
    preset: "engineering-default",
    engines: ["local", "multica"],
    watermarkAt: "2026-06-11T18:25:00",
  },
];

/* ---------------- 文档骨架 ---------------- */

const FULL_PACK: Omit<DocEntry, "present">[] = [
  { path: "contract.md", get title() { return t("model.mockWork.missionContract"); }, group: "required", required: true },
  { path: "task_flow.md", get title() { return t("model.mockWork.stageProcess"); }, group: "required", required: true },
  { path: "plan/milestones.md", get title() { return t("model.mockWork.milestonePlan"); }, group: "plan", required: false },
  { path: "plan/strategy.md", get title() { return t("model.mockWork.implementationStrategy"); }, group: "plan", required: false },
  { path: "design/decisions.md", get title() { return t("model.mockWork.designDecisions"); }, group: "design", required: false },
  { path: "design/visual-map.md", get title() { return t("model.mockWork.visualMap"); }, group: "design", required: false },
  { path: "progress/log.md", get title() { return t("model.mockWork.progressRecord"); }, group: "progress", required: false },
  { path: "review/walkthrough.md", get title() { return t("model.mockWork.walkthrough"); }, group: "closeout", required: true },
  { path: "review/lessons.md", get title() { return t("model.mockWork.experienceAccumulation"); }, group: "closeout", required: false },
  { path: "evidence/run-log.md", get title() { return t("model.mockWork.evidenceExecution"); }, group: "evidence", required: true },
];

/** missing 传入缺失文档的 path 列表 */
const docs = (missing: string[] = []): DocEntry[] =>
  FULL_PACK.map((d) => ({ ...d, present: !missing.includes(d.path) }));

/* ---------------- 任务 ---------------- */

type TaskSeed = Partial<TaskRow> &
  Pick<TaskRow, "taskId" | "title" | "coordinationStatus" | "module">;

const T = (s: TaskSeed): TaskRow => ({
  projectId: "harness-anything",
  rawStatus: s.coordinationStatus as string,
  freshness: "fresh",
  packageDisposition: "active",
  closeoutReadiness: "not_required",
  engine: "local",
  source: "local-document",
  lastKnownAt: "2026-06-12T09:00:00",
  gates: [],
  docs: docs(),
  attribution: { originator: null, latestActor: null, trailCount: 0, completeness: "unresolved" },
  ...s,
});

export const MOCK_TASKS: TaskRow[] = [
  /* ===== harness-anything · kernel ===== */
  T({
    taskId: "KER-101",
    get title() { return t("model.mockWork.writeCoordinatorSerialWritingConflictReconstruction"); },
    coordinationStatus: "active",
    module: "kernel",
    closeoutReadiness: "incomplete",
    lastKnownAt: "2026-06-12T09:42:00",
    gates: [
      { name: "schema-check", ok: true },
      { name: "import-boundary", ok: true },
    ],
    docs: docs(["review/walkthrough.md", "evidence/run-log.md"]),
  }),
  T({
    taskId: "KER-102",
    get title() { return t("model.mockWork.threePortSchemaContractVerificationPipeline"); },
    coordinationStatus: "in_review",
    module: "kernel",
    closeoutReadiness: "ready",
    waitingSince: "2026-06-12T08:15:00",
    lastKnownAt: "2026-06-12T08:15:00",
    gates: [
      { name: "materialization", ok: true },
      { name: "check", ok: true },
    ],
  }),
  T({
    taskId: "KER-108",
    get title() { return t("model.mockWork.relationEntityProvenanceField"); },
    coordinationStatus: "planned",
    module: "kernel",
    docs: docs(["design/visual-map.md", "progress/log.md", "review/walkthrough.md", "review/lessons.md", "evidence/run-log.md"]),
  }),
  T({
    taskId: "KER-109",
    get title() { return t("model.mockWork.writeCoordinatorLockCompetitionStressTest"); },
    coordinationStatus: "blocked",
    module: "kernel",
    closeoutReadiness: "missing",
    gates: [{ name: "stress-bench", ok: false, get detail() { return t("model.mockWork.p99WriteDelayExceedsThreshold"); } }],
    docs: docs(["review/walkthrough.md", "evidence/run-log.md"]),
  }),
  /* ===== harness-anything · store ===== */
  T({
    taskId: "KER-103",
    get title() { return t("model.mockWork.artifactStoreDirectoryLayoutScaffoldGenerator"); },
    coordinationStatus: "planned",
    module: "store",
    lastKnownAt: "2026-06-11T17:20:00",
    docs: docs(["plan/strategy.md", "design/visual-map.md", "review/walkthrough.md", "evidence/run-log.md"]),
  }),
  T({
    taskId: "KER-107",
    get title() { return t("model.mockWork.projectionWatermarkIncrementalRefresh"); },
    coordinationStatus: "active",
    module: "store",
    closeoutReadiness: "incomplete",
    lastKnownAt: "2026-06-12T07:30:00",
  }),
  T({
    taskId: "STO-210",
    get title() { return t("model.mockWork.artifactStorePathTraversalProtection"); },
    coordinationStatus: "in_review",
    module: "store",
    closeoutReadiness: "ready",
    waitingSince: "2026-06-11T15:00:00",
    lastKnownAt: "2026-06-11T15:00:00",
    gates: [
      { name: "materialization", ok: true },
      { name: "security-check", ok: true },
    ],
  }),
  T({
    taskId: "STO-211",
    get title() { return t("model.mockWork.tombstoneGcStrategy"); },
    coordinationStatus: "planned",
    module: "store",
    docs: docs(["plan/milestones.md", "design/decisions.md", "review/walkthrough.md", "evidence/run-log.md"]),
  }),
  /* ===== harness-anything · cli ===== */
  T({
    taskId: "KER-104",
    get title() { return t("model.mockWork.projectionRebuildCommandGovernanceRebuild"); },
    coordinationStatus: "done",
    module: "cli",
    closeoutReadiness: "passed",
    lastKnownAt: "2026-06-10T16:03:00",
  }),
  T({
    taskId: "CLI-310",
    get title() { return t("model.mockWork.harnessCheckIncrementalSnapshotCommand"); },
    coordinationStatus: "active",
    module: "cli",
    closeoutReadiness: "incomplete",
    lastKnownAt: "2026-06-12T08:50:00",
  }),
  T({
    taskId: "CLI-311",
    get title() { return t("model.mockWork.harnessInitTemplateMaterialization"); },
    coordinationStatus: "done",
    module: "cli",
    closeoutReadiness: "passed",
    lastKnownAt: "2026-06-09T14:12:00",
  }),
  /* ===== harness-anything · gui ===== */
  T({
    taskId: "KER-105",
    get title() { return t("model.mockWork.oldVersionDashboardFieldCleaning"); },
    coordinationStatus: "cancelled",
    module: "gui",
    packageDisposition: "archived",
    lastKnownAt: "2026-06-08T11:30:00",
  }),
  T({
    taskId: "GUI-401",
    get title() { return t("model.mockWork.sevenViewNavigationShellThemeSystem"); },
    coordinationStatus: "active",
    module: "gui",
    closeoutReadiness: "incomplete",
    lastKnownAt: "2026-06-12T10:01:00",
  }),
  T({
    taskId: "GUI-402",
    get title() { return t("model.mockWork.kanbanBatchOperationInteraction"); },
    coordinationStatus: "planned",
    module: "gui",
    docs: docs(["design/visual-map.md", "review/walkthrough.md", "evidence/run-log.md"]),
  }),
  T({
    taskId: "GUI-403",
    get title() { return t("model.mockWork.electronSecurityContractCspLaunched"); },
    coordinationStatus: "blocked",
    module: "gui",
    closeoutReadiness: "missing",
    gates: [{ name: "security-contract", ok: false, get detail() { return t("model.mockWork.cspWhitelistNotFrozen"); } }],
    docs: docs(["review/walkthrough.md", "evidence/run-log.md"]),
  }),
  /* ===== harness-anything · adapters ===== */
  T({
    taskId: "FAI-37",
    get title() { return t("model.mockWork.taskBindingSchemaThreeAxisProjection"); },
    coordinationStatus: "blocked",
    rawStatus: "waiting_local_directory",
    module: "adapters",
    engine: "multica",
    source: "snapshot-cache",
    freshness: "stale-but-usable",
    closeoutReadiness: "missing",
    lastKnownAt: "2026-06-12T07:55:00",
    docs: docs(["review/walkthrough.md", "evidence/run-log.md"]),
  }),
  T({
    taskId: "GH-2214",
    get title() { return t("model.mockWork.gitHubIssuesAdapterStatusMappingTable"); },
    coordinationStatus: "active",
    rawStatus: "open:in-progress",
    module: "adapters",
    engine: "multica",
    source: "external-engine",
    closeoutReadiness: "incomplete",
    lastKnownAt: "2026-06-12T09:10:00",
  }),
  T({
    taskId: "LIN-88",
    get title() { return t("model.mockWork.linearAdapterIncrementalSnapshotPolling"); },
    coordinationStatus: "unknown",
    rawStatus: "triage_hold",
    module: "adapters",
    engine: "multica",
    source: "snapshot-cache",
    freshness: "stale-but-usable",
    closeoutReadiness: "missing",
    lastKnownAt: "2026-06-11T22:40:00",
    docs: docs(["review/walkthrough.md", "evidence/run-log.md"]),
  }),
  T({
    taskId: "LIN-92",
    get title() { return t("model.mockWork.closeoutNoteReleasePipeline"); },
    coordinationStatus: "in_review",
    rawStatus: "Finalizing",
    module: "adapters",
    engine: "multica",
    source: "snapshot-cache",
    freshness: "unavailable-no-cache",
    closeoutReadiness: "ready",
    waitingSince: "2026-06-10T19:12:00",
    lastKnownAt: "2026-06-10T19:12:00",
    gates: [{ name: "snapshot-fresh", ok: false, get detail() { return t("model.mockWork.snapshotCacheNotAvailable"); } }],
  }),
  T({
    taskId: "ADP-501",
    get title() { return t("model.mockWork.gitHubStatusMapCompletion"); },
    coordinationStatus: "in_review",
    rawStatus: "open:review",
    module: "adapters",
    engine: "multica",
    source: "external-engine",
    closeoutReadiness: "ready",
    waitingSince: "2026-06-12T06:40:00",
    lastKnownAt: "2026-06-12T09:30:00",
    gates: [{ name: "check", ok: true }],
  }),
  T({
    taskId: "ADP-502",
    get title() { return t("model.mockWork.multicaSnapshotCachingLayer"); },
    coordinationStatus: "done",
    rawStatus: "done",
    module: "adapters",
    engine: "multica",
    source: "snapshot-cache",
    closeoutReadiness: "passed",
    lastKnownAt: "2026-06-09T20:05:00",
  }),
  /* ===== harness-anything · ci ===== */
  T({
    taskId: "KER-106",
    get title() { return t("model.mockWork.importBoundaryTestCoverageGuiPackage"); },
    coordinationStatus: "in_review",
    module: "ci",
    closeoutReadiness: "ready",
    waitingSince: "2026-06-12T09:58:00",
    lastKnownAt: "2026-06-12T09:58:00",
    gates: [
      { name: "materialization", ok: true },
      { name: "check", ok: true },
    ],
  }),
  T({
    taskId: "CI-601",
    get title() { return t("model.mockWork.importBoundaryTestMatrix"); },
    coordinationStatus: "active",
    module: "ci",
    closeoutReadiness: "incomplete",
    lastKnownAt: "2026-06-12T09:20:00",
  }),
  T({
    taskId: "CI-602",
    get title() { return t("model.mockWork.guiPackageE2eSmokeTest"); },
    coordinationStatus: "in_review",
    module: "ci",
    closeoutReadiness: "failed",
    lastKnownAt: "2026-06-11T16:45:00",
    gates: [{ name: "e2e", ok: false, get detail() { return t("model.mockWork.threeUseCasesTimedOut"); } }],
  }),

  /* ===== coding-agent-harness ===== */
  T({
    taskId: "DOC-11",
    get title() { return t("model.mockWork.kernelRewriteDocumentNavigationReorganization"); },
    coordinationStatus: "active",
    module: "docs",
    projectId: "coding-agent-harness",
    closeoutReadiness: "incomplete",
    lastKnownAt: "2026-06-12T09:35:00",
  }),
  T({
    taskId: "DOC-12",
    get title() { return t("model.mockWork.guiSpecSevenViewRevision"); },
    coordinationStatus: "in_review",
    module: "docs",
    projectId: "coding-agent-harness",
    closeoutReadiness: "ready",
    waitingSince: "2026-06-12T09:55:00",
    lastKnownAt: "2026-06-12T09:55:00",
    gates: [{ name: "materialization", ok: true }],
  }),
  T({
    taskId: "DOC-13",
    get title() { return t("model.mockWork.adapterPrdTemplateUnification"); },
    coordinationStatus: "planned",
    module: "docs",
    projectId: "coding-agent-harness",
    docs: docs(["design/decisions.md", "review/walkthrough.md", "evidence/run-log.md"]),
  }),
  T({
    taskId: "TPL-21",
    get title() { return t("model.mockWork.dashboardTemplateExtraction"); },
    coordinationStatus: "done",
    module: "templates",
    projectId: "coding-agent-harness",
    closeoutReadiness: "passed",
    lastKnownAt: "2026-06-08T15:40:00",
  }),
  T({
    taskId: "TPL-22",
    get title() { return t("model.mockWork.presetBilingualTemplateImage"); },
    coordinationStatus: "blocked",
    module: "templates",
    projectId: "coding-agent-harness",
    closeoutReadiness: "missing",
    docs: docs(["review/walkthrough.md", "evidence/run-log.md"]),
    lastKnownAt: "2026-06-11T11:00:00",
  }),
  T({
    taskId: "DSH-31",
    get title() { return t("model.mockWork.legacyDashboardRetirementList"); },
    coordinationStatus: "cancelled",
    module: "dashboard",
    projectId: "coding-agent-harness",
    packageDisposition: "archived",
    lastKnownAt: "2026-06-07T10:00:00",
  }),
  T({
    taskId: "DSH-32",
    get title() { return t("model.mockWork.issueSynchronizationScriptMigration"); },
    coordinationStatus: "active",
    rawStatus: "open:in-progress",
    module: "dashboard",
    projectId: "coding-agent-harness",
    engine: "multica",
    source: "external-engine",
    closeoutReadiness: "incomplete",
    lastKnownAt: "2026-06-12T08:05:00",
  }),

  /* ===== rag-pipeline-svc ===== */
  T({
    taskId: "RAG-1",
    get title() { return t("model.mockWork.incrementalIngestionPipeline"); },
    coordinationStatus: "active",
    module: "ingest",
    projectId: "rag-pipeline-svc",
    closeoutReadiness: "incomplete",
    lastKnownAt: "2026-06-11T17:55:00",
  }),
  T({
    taskId: "RAG-2",
    get title() { return t("model.mockWork.hybridSearchWeightParameterAdjustment"); },
    coordinationStatus: "planned",
    module: "retrieval",
    projectId: "rag-pipeline-svc",
    docs: docs(["plan/strategy.md", "review/walkthrough.md", "evidence/run-log.md"]),
  }),
  T({
    taskId: "RAG-3",
    get title() { return t("model.mockWork.reorderProviderInterface"); },
    coordinationStatus: "in_review",
    rawStatus: "Finalizing",
    module: "retrieval",
    projectId: "rag-pipeline-svc",
    engine: "multica",
    source: "snapshot-cache",
    freshness: "stale-but-usable",
    closeoutReadiness: "ready",
    waitingSince: "2026-06-11T13:20:00",
    lastKnownAt: "2026-06-11T13:20:00",
    gates: [{ name: "check", ok: true }],
  }),
  T({
    taskId: "RAG-4",
    get title() { return t("model.mockWork.evaluationSetFrozen"); },
    coordinationStatus: "blocked",
    module: "eval",
    projectId: "rag-pipeline-svc",
    closeoutReadiness: "missing",
    docs: docs(["review/walkthrough.md", "evidence/run-log.md"]),
    lastKnownAt: "2026-06-10T09:30:00",
  }),
  T({
    taskId: "RAG-5",
    get title() { return t("model.mockWork.offlineIndicatorBaseline"); },
    coordinationStatus: "done",
    module: "eval",
    projectId: "rag-pipeline-svc",
    closeoutReadiness: "passed",
    lastKnownAt: "2026-06-09T19:00:00",
  }),
  T({
    taskId: "RAG-6",
    get title() { return t("model.mockWork.queueBacklogManagement"); },
    coordinationStatus: "unknown",
    rawStatus: "backlog_grooming",
    module: "ingest",
    projectId: "rag-pipeline-svc",
    engine: "multica",
    source: "snapshot-cache",
    freshness: "stale-but-usable",
    closeoutReadiness: "missing",
    lastKnownAt: "2026-06-11T08:15:00",
    docs: docs(["review/walkthrough.md", "evidence/run-log.md"]),
  }),
];
