import assert from "node:assert/strict";
import test from "node:test";
import * as kernel from "../../src/index.ts";

// Golden snapshot of the kernel's public runtime surface. A diff here is a
// deliberate interface change: update this list in the same commit and say
// why in the commit message. Types are checked by the curated index files.
const publicRuntimeSurface = [
  "ActorKindSchema",
  "ActorRefSchema",
  "ArtifactStore",
  "DecisionPackageSchema",
  "DecisionStateSchema",
  "DocsReleasePromotionBundleSchema",
  "DomainStatusSchema",
  "EntityRelationRecordSchema",
  "EntityRelationsSchema",
  "FreshnessSchema",
  "HarnessCheckReportSchema",
  "HarnessConfigSchema",
  "LegacyCollisionReportSchema",
  "LegacyEvidencePointerSchema",
  "LegacyIndexEntrySchema",
  "LegacyIndexSchema",
  "LifecycleBindingSchema",
  "LifecycleEngine",
  "LinkKindSchema",
  "PresetEntrypointSchema",
  "PresetManifestSchema",
  "PresetProfileSchema",
  "ProjectionWarningCodeSchema",
  "ProjectionWarningSourceSchema",
  "PublishableProjectionSchema",
  "RedactionFindingSchema",
  "RelationDirectionSchema",
  "RelationOriginSchema",
  "RelationStateSchema",
  "RelationStrengthSchema",
  "RelationTypeSchema",
  "Sha256FingerprintSchema",
  "SnapshotStatusSchema",
  "SqliteTaskRowSchema",
  "TaskFrontmatterSchema",
  "TaskSnapshotSchema",
  "TemplateCatalogSchema",
  "TemplateLibrary",
  "TemplateSelectionSchema",
  "VerticalDefinitionSchema",
  "WriteCoordinator",
  "WriteJournalOpSchema",
  "buildPublishableProjection",
  "canonicalRelationIdentityInput",
  "checkTaskProjection",
  "closeoutReadinesses",
  "createEntityKindRegistry",
  "createInMemoryPublishIdempotencyLedger",
  "createTaskIdentity",
  "decisionStates",
  "defaultTaskProjectionPath",
  "deriveRelationId",
  "domainStatuses",
  "explainDecisionStateTransition",
  "explainStatusTransition",
  "findEntityRefs",
  "formatRelationFlowRecord",
  "formatTemplateRef",
  "getEntityKind",
  "hashTaskProjectionRows",
  "immutableBindingFields",
  "isCloseoutReadiness",
  "isDecisionState",
  "isDomainStatus",
  "isPackageDisposition",
  "isTerminalStatus",
  "needsReviewArtifacts",
  "openDomainStatuses",
  "packageDispositions",
  "parseEntityRef",
  "parseWriteEntityId",
  "planTemplateMaterialization",
  "readTaskProjection",
  "rebuildTaskProjection",
  "relationDirections",
  "relationOrigins",
  "relationStates",
  "relationStrengths",
  "relationTypes",
  "requiredSchemaIds",
  "reservePublishIdempotencyKey",
  "reviewArtifactStatuses",
  "schemaRegistry",
  "statusCoarseClass",
  "taskEntityId",
  "taskIdFromEntityId",
  "terminalDomainStatuses",
  "validateExtensionInputShape",
  "validateLifecycleBindingInvariant",
  "validatePresetManifests",
  "validateRelationRecordsForHost",
  "validateTemplateCatalog",
  "validateVerticalDefinition"
];

test("kernel public runtime surface matches the golden snapshot", () => {
  assert.deepEqual(Object.keys(kernel).sort(), publicRuntimeSurface);
});
